/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blok.gui;

import blok.engine.JBox2D;
import blok.interfaces.ISimulator;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URL;

/**
 *
 * @author sandroandrade
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public static MainWindow instance;
    
    protected MainWindow() {
        initComponents();
        Dimension size = new Dimension(1000, 600);

        MainPanel mainPanel = MainPanel.getInstance();
        mainPanel.setPreferredSize(size);
        mainPanel.setMinimumSize(size);
        mainPanel.setMaximumSize(size);
        mainPanel.setSize(size);
        setContentPane(mainPanel);

        setResizable(false);
        pack();

        ISimulator simulator = new JBox2D(mainPanel);
        mainPanel.ISimulator(simulator);
        simulator.init();
        //jbox2d.start();
    }
            
    public static MainWindow getInstance(){
        if(instance == null)
            instance = new MainWindow();
        return instance;
    }


/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());
        
        
        // Adiciona o nome das f�bricas num vetor de Strings para poder adicionar ao Menu Skin
        int op = 0;
		String [] retorno = new String[2];
	    do
	    {
		      File currentDir = new File("./plugins");
		      String []plugins = currentDir.list();
		      int i;
		      URL[] jars = new URL[plugins.length];
		      String nomeFabrica[] = new String[plugins.length];
		      for (i = 0; i < plugins.length; i++)
		      {
			nomeFabrica[i] = (new File(plugins[i].split("\\.")[0])).toString();
			retorno = nomeFabrica;
		      }
	     } while (op != 0);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Skin");
		for(int i=0; i< retorno.length;i++)
        	jMenu3.add(retorno[i].toString());//Implementar as a��es
		jMenu3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				
			}
		});
		
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);
        
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
